# The start symbol is START.

# These two rules are required; choose their weights carefully!
# S1 is the start symbol of the grammar you construct
# S2 is the start symbol of the markov grammar that is the default fallback.
99	START	S1
1	START	S2
#Declarative sentences
1 S1 S .
1 S SNP VP #subject NP
1 SNP NP
100 SNP sNP #NP specifically marked with subject, e.g., she
1 S SNP_pl VP_pl #subject NP
1 SNP_pl NP_pl
100 SNP_pl sNP_pl #NP specifically marked with subject, e.g., they
1 S GP VP
1 ONP NP_all #object NP
100 ONP oNP_all #NP specifically marked with object, e.g., her

#Interrogative sentences
.1 S1 Q ?

#Imperative sentences
.1 S1 Imp !
.1 S1 Imp .

###VERBS#############################################
#Verb basics
.2 VP VP PP
.2 VP_pl VP_pl PP
.1 VP VP conj VP
.1 VP_pl VP_pl conj VP_pl

#Adverbs
.3 VP VP Adv
.5 VP_pl VP_pl Adv

#Copula - pres sing #is yellow, is PP
1 VP BE PP
1	VP BE AP
#Copula - pres pl
1	VP_pl BE_pl PP
1	VP_pl BE_pl AP
#Copula - past sing #was yellow, was PP
1	VP BE_p PP
1	VP BE_p AP
#Copula - past pl
1	VP_pl BE_pl_p PP
1	VP_pl BE_pl_p AP
#Copula - #might be yellow, might be PP
1 VP Modal BE_inf PP
1 VP Modal BE_inf AP
1 VP_pl Modal BE_inf PP
1 VP_pl Modal BE_inf AP
#Copula - #might have been
1 VP Modal HAVE_inf BE_pp PP
1 VP Modal HAVE_inf BE_pp AP
1 VP_pl Modal HAVE_inf BE_pp PP
1 VP_pl Modal HAVE_inf BE_pp AP

#Copula: is being yellow - pres
1 VP BE BE_cont AP #sing
1 VP_pl BE_pl BE_cont AP #pl
#was being being yellow - past
1 VP BE_p BE_cont AP #sing
1 VP_pl BE_pl_p BE_cont AP #pl

#Copula: has been yellow
1 VP HAVE BE_pp AP #sing
1 VP HAVE_pl BE_pp AP #pl

#Copula: has been being
1 VP HAVE BE_pp BE_cont AP #sing
1 VP HAVE_pl BE_pp BE_cont AP #pl

#Verbs - pres sing. #he drinks
100	VP VerbT ONP
1	VP VerbI
.3 VP VerbC CC
#Verbs - pres pl
1	VP_pl VerbT_pl ONP
1	VP_pl VerbI_pl
.3 VP_pl VerbC_pl CC

#Verbs - past sing. #he drank
1	VP VerbT_p ONP
1	VP VerbI_p
.3 VP VerbC_p CC
#Verbs - past pl.
1	VP_pl VerbT_pl_p ONP
1	VP_pl VerbI_pl_p
.3 VP_pl VerbC_pl_p CC


#Present continuous - sing. #is drinking
1	VP BE	GP #sing
1	VP_pl BE_pl	GP #pl
#Past continuous
1	VP BE_p	GP #sing
1	VP_pl BE_pl_p	GP #pl

#Present Simple Passive #is drunk (Note: only transitive)
1 VP BE VerbT_pp #sing
1 VP_pl BE_pl VerbT_pp #pl
#Past Simple Passive
1 VP BE_p VerbT_pp #sing
1 VP_pl BE_pl_p VerbT_pp #pl

#Present Continuous Passive #is being drunk (Note: only transitive.)
1 VP BE BE_cont VerbT_pp #sing
1 VP_pl BE_pl BE_cont VerbT_pp #pl
#Past Continuous Passive
1 VP BE_p BE_cont VerbT_pp #sing
1 VP_pl BE_pl_p BE_cont VerbT_pp #pl

#Present Perfect #has drunk
1 VP HAVE PPP #sing
1 VP_pl HAVE_pl PPP #pl
#Past Perfect #had drunk
1 VP HAVE_p PPP #sing
1 VP_pl HAVE_pl_p PPP #pl

#Present Perfect Passive #has been drunk (Note: only transitive)
1 VP HAVE BE_pp VerbT_pp #sing
1 VP_pl HAVE_pl BE_pp VerbT_pp #pl
#Past Perfect Passive #had been drunk
1 VP HAVE_p BE_pp VerbT_pp #sing
1 VP_pl HAVE_pl_p BE_pp VerbT_pp #pl

#Present Perfect Continuous #has been drinking
1	VP HAVE BE_pp	GP #sing
1	VP_pl HAVE_pl BE_pp	GP #pl
#Past Perfect Continuous #had been drinking
1	VP HAVE_p BE_pp	GP #sing
1	VP_pl HAVE_pl_p BE_pp	GP #pl

#Future (will) #will drink
#Future Possibility #might drink
#Present Modal #should drink
1 VP Modal VinfP #sing
1 VP_pl Modal VinfP #pl

#Future (will) Passive #will be drunk (Note: only transitive)
1 VP Modal BE_inf VerbT_pp
1 VP_pl Modal BE_inf VerbT_pp

#Future Continuous #will be drinking #Future Possible continuous
1 VP Modal BE_inf GP
1 VP_pl Modal BE_inf GP

#Future Perfect #will have drunk
#Past Modal #should have drunk
#Past Unreal Conditional #would have drunk
1 VP Modal HAVE_inf PPP
1 VP_pl Modal HAVE_inf PPP

#Unknown #should have been drinking
1 VP Modal HAVE_inf BE_pp GP
1 VP_pl Modal HAVE_inf BE_pp GP

#Unknown #should have been drunk (Note: only transitive)
1 VP Modal HAVE_inf BE_pp VerbT_pp
1 VP_pl Modal HAVE_inf BE_pp VerbT_pp


#TODO: incorporate these conditional statements.
#TODO #Real Conditional #if he drinks wine, I will drive home
#TODO #Unreal Conditional #if he drank wine, I would drive home.
#TODO #Past Unreal Conditional #If he had drunk wine, I would have driven home.



###NOUNS#############################################
#Group of NP and NP_pl
1 NP_all NP
1 NP_all NP_pl

#Basic NP
.2 NP NP PP
1 NP Proper
1 NP Det Noun
#Basic NP plural
.1 NP_pl NP_pl PP
.05 NP_pl NP conj NP
.05 NP_pl NP_pl conj NP_pl
1 NP_pl Noun_pl
.2 NP_pl Det_pl Noun_pl
.2 NP_pl Proper_pl
#Numbers
.3 NP_pl Num Noun_pl
.1 NP_pl Num Proper_pl

#Basic PP
1	PP Prep NP
1	PP Prep NP_pl

#Basic Noun
2	Noun AP Noun
2	Noun_pl AP Noun_pl

#NP qualified with "that", e.g., "the castle that was his home"
.05 NP NP Comp VP
.05 NP_pl NP_pl Comp VP_pl

#Possessive pronouns e.g. "his"
#TODO: does not agree with antecedent yet
.2 NP PRP_poss Noun
.2 NP_pl PRP_poss Noun_pl

#Pronouns
#TODO: need to distinguish NP that is subject vs object
100 sNP PRP_subj
100 sNP_pl PRP_subj_pl
100 oNP_all oNP
100 oNP_all oNP_pl
100 oNP PRP_obj
100 oNP_pl PRP_obj_pl




###OTHER##############################################

#Adjective phrase
1 AP JJ
.1 AP Adv JJ

#Complementizer
1 CC Comp S
1 CC S #hidden "that"

#Gerund phrases
1 GP GP PP
1 GP VerbT_G ONP
1 GP VerbI_G
.2 GP VerbG_C CC

#Past participle phrases
1 PPP VerbT_pp ONP
1 PPP VerbI_pp
1 PPP VerbC_pp CC

#Infinitive verb phrase
1 VinfP VinfT ONP
1 VinfP VinfI
1 VinfP Vinf_C CC

#Nonrestrictive clause #"Arthur, (who is) sixty inches, ..."
#TODO: doesn't work for more than 1 NRC linked together (multiple commas) or end of sentence
#TODO: include pronouns
.01 NP NP NRC
.01 NP_pl NP_pl NRC
.01 NRC , NP_all ,
.01 NRC , NP_all #TODO: TEMPORARY FIX for end of sentences
#TODO: add "who is sixty inches"

###IMPERATIVE SENTENCES################################################
1 Imp do_imp VinfP
1 Imp do_imp Neg VinfP

###QUESTIONS################################################
#TODO: distinguish T from I verbs; "what do strangers migrate ? " is wrong
# "does her king suggest Uther Pendragon carry ?" is wrong

 1 Q Q_do
 1 Q Q_wh
 1 Q Q_is

 1 Q_wh Wh_pronouns Q_do
 1 Q_wh Wh_adverbs Q_do

 1 Q_do do_sing Vinf_Cl #e.g. does the coconut drink ?
 1 Q_do do_pl Vinf_Cl_pl #e.g. do coconuts drink ?
 1 Q_do do_sing InfP #e.g. does arthur suggest she drink ?

 1 Vinf_subjunct_Cl Vinf_subjunct Vinf_Cl
 1 Vinf_subjunct_Cl Vinf_subjunct Vinf_Cl_pl

 1 Vinf_Cl NP VinfP
 1 Vinf_Cl_pl NP_pl VinfP
 1 Vinf_Cl_subjunct Vinf_subjunct NP VinfP_OI


# Verb, infinitive, intransitive - needs no second object.
 1 VinfP VinfI
 # Verb, infinitive, intransitive, works with PP
 1 VinfP VinfIPP PP
# Verb, transitive, requires one direct object
 1 VinfP VinfT NP
 # Verb, transitiv, requires one direct object, works with PP
 1 VinfP VinfTPP NP PP

 # Verb infinitive with object implied (as in who does Arthur suggest she carry ?)
 1 VinfP_OI	VinfT
 1 VinfP_OI	VinfTPP	PP

 1 VP_inf_ext V_inf_1 NP

 1 Q_is Is_phrase_pl PresPP
 1 Q_is Is_phrase PresPP

 1 Is_phrase BE PRP_subj
 1 Is_phrase BE_p PRP_subj
 1 Is_phrase_pl BE_pl PRP_subj_pl
 1 Is_phrase_pl BE_pl_p PRP_subj_pl

 1 PresPP VerbG
 1 PresPP VerbG_C Vinf_Cl
 1 InfP NP Vinf_Cl_subjunct
# This is a hand_generated set of preterminal rules.
# It specifies a simple tag set which will be handled by the S2
# grammar and which can (though doesn't necessarily need to be)
# handled by the S1 grammar.
#
# The weights given here may be changed, but no new vocabulary
# items are to be added.

# Miscellaneous items that don't fit into any of our simple tags are
# given to Misc.  You will want to develop your own tags for these!

# Determiners. Note these are all for singular Nouns.
1	Det	a
1	Det	another
1	Det	any
1	Det	each
1	Det	every
1	Det one #moved from numbers to Dets
1	Det	no
1	Det	that
1	Det	the
1	Det	this

1	Det_pl	the

# Prepositions.
1	Prep	above
1	Prep	across
1	Prep	at
1	Prep	below
1	Prep	by
1	Prep	for
1	Prep	from
1	Prep	into
1	Prep	near
1	Prep	of
1	Prep	on
1	Prep	over
1	Prep	through
1	Prep 	to
1	Prep	with

###ADJECTIVES#################################################################

# Adjectives.
1	JJ	weary
1	JJ	bloody
1	JJ	unable
1	JJ	trusty
1	JJ	further
1	JJ	sacred
1	JJ	tropical
1	JJ	indigenous
1	JJ	temperate
1	JJ	hot
1	JJ	lucky
1	JJ	simple
1	JJ	tiny
1	JJ	hard
1	JJ	sensational
1	JJ	comparable
1	JJ	angolian
1	JJ	yellow
1	JJ	plodding

# Comparative adjectives.
1	JJcomp	bloodier
1	JJcomp	wearier
1	JJcomp	trustier
1	JJcomp	hotter
1	JJcomp	simpler
1	JJcomp	tinier
1	JJcomp	harder

# Superlative adjectives.
1	JJsup	bloodiest
1	JJsup	weariest
1	JJsup	trustiest
1	JJsup	hottest
1	JJsup	simplest
1	JJsup	tiniest
1	JJsup	hardest

###VERBS#####################################################

#TODO: Special verbs that require certain prepositions afterwards
#e.g., "migrates to"?

######################TODO############


#TODO: break up Vinf to I and T forms and others as needed
# Verbs (base form) (infinitive)

# Verb, infinitive, intransitive - needs no second object.
# Does NP VinfI ?
1 	VinfI	speak
1 	VinfI	ride
1 	VinfI	grow
1 	VinfI	drink
1 	VinfI	migrate
1 	VinfI	know

# Verb, transitive, requires one direct object.
# Does NP VinfT NP ?
1	VinfT 	have
1	VinfT 	cover
1	VinfT 	drink
1	VinfT 	grow
1	VinfT 	carry
1	VinfT 	know
1	VinfT 	ride
# 1	VinfT 	speak - maybe??? Only really valid with languages. Is that grammatical tho?


# Verb, infinitive, intransitive, works with PP
# Does NP VinfIPP PP ?
1 	VinfIPP	speak
1 	VinfIPP	ride
1 	VinfIPP	grow
1 	VinfIPP	drink
1 	VinfIPP	migrate

# Verb, transitive, requires one direct object, works with PP
# Does NP VinfTPP NP PP ?
# 1	VinfTPP 	have # Works with locations, but not that generally. Have a coconut on the bridge, not have a coconut to the bridge
# 1	VinfTPP 	cover # only seems to work with "with"
1	VinfTPP 	drink
1	VinfTPP 	grow
1	VinfTPP 	carry
1	VinfTPP 	know
1	VinfTPP 	ride
# 1	VinfTPP 	speak - maybe??? Only really valid with languages. Is that grammatical tho?



1	Vinf	have
1	Vinf	speak #TODO weird with what questions: (what does arthur speak) but might be fine (e.g. what language does arthur speak)
1	Vinf	cover
1	Vinf	be #TODO this is weird in questions (does arthur be? do coconuts be?)
1	Vinf	ride
1	Vinf	drink
1	Vinf	grow
1	Vinf	carry
1	Vinf	suggest
1	Vinf	migrate
1	Vinf	know

# Subjunctive - see https://www.englishpage.com/minitutorials/subjunctive.html
# also might be used to trip up other teams
1 Vinf_subjunct suggest

# Verbs (infinite) (one argument)
1 V_inf_1 have
1 V_inf_1 cover
1 V_inf_1 ride
1 V_inf_1 drink
1 V_inf_1 grow
1 V_inf_1 carry
1 V_inf_1 suggest
1 V_inf_1 know
###################### End TODO############

# Copula
1	BE is
1 BE_p was
1	BE_pl	are
1	BE_pl_p	were
1	BE_pp been
1	BE_cont being #is being drunk; is being JJ
1 BE_inf be

# Have as auxillary
1 HAVE has
1 HAVE_pl have
1	HAVE_p had
1	HAVE_pl_p had
1 HAVE_inf have

# Modals.
1	Modal	can
1	Modal	could
1	Modal	may
1	Modal	might
1	Modal	must
1	Modal	ought to
1	Modal	shall
1	Modal	should
1	Modal	will
1	Modal	would


# Verbs (base form) (infinitive)
# Transitive
1	VinfT	have
1	VinfT	speak
1	VinfT	cover
1	VinfT	be
1	VinfT	ride
1	VinfT	drink
1	VinfT	grow
1	VinfT	carry
1	VinfT	suggest
1	VinfT	know

#Intransitive
1	VinfI	speak
1	VinfI	be
1	VinfI	ride
1	VinfI	drink
1	VinfI	grow
1	VinfI	suggest
1	VinfI	migrate
1	VinfI	know

# Followed by complementizer
1 Vinf_C suggest
1 Vinf_C know


# Verbs (third person singular present).
# Note that only transitive verbs get our VerbT tag,
# and some of those could also function as intransitives!
1	VerbT has
1	VerbT covers
1	VerbT drinks
1	VerbT	carries
1	VerbT	rides
1	VerbT	grows
1 VerbT suggests
1	VerbT	knows
1 VerbT is

#Verbs followed by complementizer
1	VerbC	suggests
1	VerbC	knows

#Verbs (third person singular present) _ Intransitive
1	VerbI drinks
1	VerbI rides
1	VerbI	speaks
1	VerbI	grows
1	VerbI	goes
1	VerbI	migrates
1	VerbI	knows

# Verbs (present, plural, third person).
1	VerbT_pl	have
1	VerbT_pl	speak
1	VerbT_pl	cover
1	VerbT_pl	ride
1	VerbT_pl	drink
1	VerbT_pl	grow
1	VerbT_pl    carry
1	VerbT_pl	suggest
1	VerbT_pl	know
1   VerbT_pl are

# Verbs (present, plural, third person). _ Intransitive
#TODO: why are they missing "go"? "Goes" exists...
1	VerbI_pl drink
1	VerbI_pl ride
1	VerbI_pl	speak
1	VerbI_pl	grow
1	VerbI_pl	migrate
1	VerbI_pl	know

#Verbs followed by complementizer - pres pl
1	VerbC_pl	suggest
1	VerbC_pl	know

# Verbs (past tense). Transitive - sing
1	VerbT_p	was
1	VerbT_p	had
1	VerbT_p	spoke
1	VerbT_p	covered
1	VerbT_p	rode
1	VerbT_p	drank
1	VerbT_p	grew
1	VerbT_p	carried
1	VerbT_p suggested
1	VerbT_p	migrated
1	VerbT_p	knew

# Verbs (past tense). Transitive - pl
1	VerbT_pl_p	were
1	VerbT_pl_p	had
1	VerbT_pl_p	spoke
1	VerbT_pl_p	covered
1	VerbT_pl_p	rode
1	VerbT_pl_p	drank
1	VerbT_pl_p	grew
1	VerbT_pl_p	carried
1	VerbT_pl_p suggested
1	VerbT_pl_p	knew

# Verbs (past tense). Intransitive - sing
1	VerbI_p	migrated
1	VerbI_p drank
1	VerbI_p rode
1	VerbI_p	spoke
1	VerbI_p	grew
1	VerbI_p	knew

# Verbs (past tense). Intransitive - pl
1	VerbI_pl_p	migrated
1	VerbI_pl_p drank
1	VerbI_pl_p rode
1	VerbI_pl_p	spoke
1	VerbI_pl_p	grew
1	VerbI_pl_p	knew

#Verbs followed by complementizer - past sing
1	VerbC_p	suggested
1	VerbC_p	knew

#Verbs followed by complementizer - past pl
1	VerbC_pl_p	suggested
1	VerbC_pl_p	knew


# Verbs (present participles). G for gerund, although not always strictly a gerund
1	VerbG	having
1	VerbG	speaking
1	VerbG	covering
1	VerbG	riding
1	VerbG	drinking
1	VerbG	growing
1	VerbG	carrying
1	VerbG	migrating
1	VerbG	knowing

# Transitive
1	VerbT_G	having
1	VerbT_G	speaking
1	VerbT_G	covering
1	VerbT_G	riding
1	VerbT_G	drinking
1	VerbT_G	growing
1	VerbT_G	carrying
1	VerbT_G	knowing

# Intransitive
1	VerbI_G	migrating
1	VerbI_G	speaking
1	VerbI_G	riding
1	VerbI_G	drinking
1	VerbI_G	growing
1 VerbI_G	knowing

#Gerund with complentizer that
#"is/was knowing that" ungrammatical
1 VerbG_C suggesting

# Verbs (past participle).
# - Transitive
1	VerbT_pp	spoken #TODO: special "to"
1	VerbT_pp	covered
1	VerbT_pp	ridden
1	VerbT_pp	drunk
1	VerbT_pp	grown
1	VerbT_pp	carried
1	VerbT_pp	suggested
1	VerbT_pp	known

# - Intransitive
1 VerbI_pp	migrated
1	VerbI_pp	suggested
1	VerbI_pp	known
1	VerbI_pp	ridden
1	VerbI_pp	drunk
1	VerbI_pp	grown
1	VerbI_pp	spoken

# - followed by complementizer
1	VerbC_pp	suggested
1	VerbC_pp	known

###NOUNS############################################################

# Proper nouns.  Note that our Proper tag is just for people.
1	Proper	Arthur
1	Proper	Guinevere
1	Proper	Sir Lancelot
1	Proper	Sir Bedevere
1	Proper	Zoot
1	Proper	Dingo
1	Proper	Patsy
1	Proper	Uther Pendragon

# Singular and mass nouns.  Notice that only the
# ones that start with consonants get our Noun tag.
1	Noun	castle
1	Noun	king
1	Noun	defeater
1	Noun	sovereign
1	Noun	servant
1	Noun	corner
1	Noun	land
1	Noun	quest
1	Noun	chalice
1	Noun	master
1	Noun	horse
1	Noun	fruit
1	Noun	swallow
1	Noun	sun
1	Noun	winter
1	Noun	coconut
1	Noun	pound
1	Noun	husk
1	Noun	home
1	Noun	weight
1	Noun	story
1	Noun	Holy Grail
1	Noun	Round Table

# Plural nouns.
1	Noun_pl	coconuts
1	Noun_pl	halves
1	Noun_pl	snows
1	Noun_pl	mountains
1	Noun_pl	areas
1	Noun_pl	strangers
1	Noun_pl	inches
1	Noun_pl	snakes
1	Noun_pl	ants
1	Noun_pl	nights

# More proper nouns, not people.

1	Proper	Camelot
1	Proper	England
1	Proper	the Holy Grail
1	Proper	the Round Table

# Plural proper nouns.
1	Proper_pl	Britons
1	Proper_pl	Saxons

# Personal pronouns (sing) (subjective)
1	PRP_subj	he
1   PRP_subj    she
1   PRP_subj    it

# Personal pronouns (sing) (objective)
1	PRP_obj	him
1   PRP_obj    her
1   PRP_obj    it

# Personal pronouns (plural) (subjective)
1	PRP_subj_pl	they

# Personal pronouns (plural) (objective)
1	PRP_obj_pl	them

# Possessive personal pronouns
1	PRP_poss her
1	PRP_poss	his
1	PRP_poss	its
1 PRP_poss their # Possessive personal pronouns (plural) #TODO: separation needed?


# un-classified pronouns
1	PRP_misc one #TODO

####################################################################

###OTHER################################################################

# Adverbs.
1	Adv	again
1	Adv	already
1	Adv	currently
1	Adv	frequently
1	Adv	precisely
1	Adv	south
1	Adv	successfully
1	Adv	unfortunately

# Numbers.
1	Num	eight
1	Num	five
1	Num	5.5
1	Num	sixty
1	Num	5,000

#TODO: much more with conjunctions
# Coordinating conjunctions, sentence_level
1 Conj and
1 Conj but

# Coordinating conjunctions, NP/VP_level
1 conj and


# End_of_sentence.
1	Misc	!
1	Misc	.
1	Misc	?

# Pauses.
1	Misc	,
1	Misc	...
1	Misc	__
1	Misc	;
1	Misc	:


# Coordinating conjunctions.
1	Misc	or
1	Misc	either
1	Misc	nor
1	Misc	neither
1	Misc	so

# Expletive.
1	Misc	there

# Complementizers
1 Comp that

# Subordinating conjunctions.
1	Misc	that
1	Misc	so
1	Misc	while
1	Misc	because
1	Misc	if

# 'do'/'does'
1	do_pl	do
1	do_sing	does
1	do_imp do #imperative mood

# 'to'
1	'to'	to

# 'not'
1	Neg	not

# Wh_determiners.
1	Misc	that
1	Misc	what
1	Misc	which

# Wh_pronouns.
1	Wh_pronouns	what
1	Wh_pronouns	who

# Wh possessive pronoun.
1	Misc	whose

# Wh_adverbs
1	Wh_adverbs	how
1	Wh_adverbs	when
1	Wh_adverbs	where
1	Wh_adverbs	why

# Possessive marker.
1	Misc	's
1	S2
1	S2	_Det
1	S2	_Misc
1	S2	_Noun
1	S2	_Prep
1	S2	_Proper
1	S2	_VerbT
1	_Det	Det
1	_Det	Det _Det
1	_Det	Det _Misc
1	_Det	Det _Noun
1	_Det	Det _Prep
1	_Det	Det _Proper
1	_Det	Det _VerbT
1	_Misc	Misc
1	_Misc	Misc _Det
1	_Misc	Misc _Misc
1	_Misc	Misc _Noun
1	_Misc	Misc _Prep
1	_Misc	Misc _Proper
1	_Misc	Misc _VerbT
1	_Noun	Noun
1	_Noun	Noun _Det
1	_Noun	Noun _Misc
1	_Noun	Noun _Noun
1	_Noun	Noun _Prep
1	_Noun	Noun _Proper
1	_Noun	Noun _VerbT
1	_Prep	Prep
1	_Prep	Prep _Det
1	_Prep	Prep _Misc
1	_Prep	Prep _Noun
1	_Prep	Prep _Prep
1	_Prep	Prep _Proper
1	_Prep	Prep _VerbT
1	_Proper	Proper
1	_Proper	Proper _Det
1	_Proper	Proper _Misc
1	_Proper	Proper _Noun
1	_Proper	Proper _Prep
1	_Proper	Proper _Proper
1	_Proper	Proper _VerbT
1	_VerbT	VerbT
1	_VerbT	VerbT _Det
1	_VerbT	VerbT _Misc
1	_VerbT	VerbT _Noun
1	_VerbT	VerbT _Prep
1	_VerbT	VerbT _Proper
1	_VerbT	VerbT _VerbT
# This is a hand-generated set of preterminal rules.
# It specifies a simple tag set which will be handled by the S2
# grammar and which can (though doesn't necessarily need to be)
# handled by the S1 grammar.
#
# The weights given here may be changed, but no new vocabulary
# items are to be added.

# Miscellaneous items that don't fit into any of our simple tags are
# given to Misc.  You will want to develop your own tags for these!


# Singular and mass nouns.  Notice that only the
# ones that start with consonants get our Noun tag.
1	Noun	castle
1	Noun	king
1	Noun	defeater
1	Noun	sovereign
1	Noun	servant
1	Noun	corner
1	Noun	land
1	Noun	quest
1	Noun	chalice
1	Noun	master
1	Noun	horse
1	Noun	fruit
1	Noun	swallow
1	Noun	sun
1	Noun	winter
1	Noun	coconut
1	Noun	pound
1	Noun	husk
1	Noun	home
1	Noun	weight
1	Noun	story

# Determiners.
1	Det	a
1	Det	another
1	Det	any
1	Det	each
1	Det	every
1	Det	no
1	Det	that
1	Det	the
1	Det	this

# Prepositions.
1	Prep	above
1	Prep	across
1	Prep	at
1	Prep	below
1	Prep	by
1	Prep	for
1	Prep	from
1	Prep	into
1	Prep	near
1	Prep	of
1	Prep	on
1	Prep	over
1	Prep	through
1	Prep	with

# Proper nouns.  Note that our Proper tag is just for people.
1	Proper	Arthur
1	Proper	Guinevere
1	Proper	Sir Lancelot
1	Proper	Sir Bedevere
1	Proper	Zoot
1	Proper	Dingo
1	Proper	Patsy
1	Proper	Uther Pendragon

# Verbs (third person singular present).
# Note that only transitive verbs get our VerbT tag,
# and some of those could also function as intransitives!
1	VerbT	has
1	VerbT	covers
1	VerbT	is
1	VerbT	drinks
1	VerbT	carries
1	VerbT	rides

# End-of-sentence.
1	Misc	!
1	Misc	.
1	Misc	?

# Pauses.
1	Misc	,
1	Misc	...
1	Misc	--
1	Misc	;
1	Misc	:

# Coordinating conjunctions.
1	Misc	and
1	Misc	but
1	Misc	or
1	Misc	either
1	Misc	nor
1	Misc	neither
1	Misc	so

# Numbers.
1	Misc	eight
1	Misc	five
1	Misc	one
1	Misc	5.5
1	Misc	sixty
1	Misc	5,000

# Expletive.
1	Misc	there

# Subordinating conjunctions.
1	Misc	that
1	Misc	so
1	Misc	while
1	Misc	because
1	Misc	if

# Modals.
1	Misc	can
1	Misc	could
1	Misc	may
1	Misc	might
1	Misc	must
1	Misc	ought
1	Misc	shall
1	Misc	should
1	Misc	will
1	Misc	would


# Adjectives.
1	Misc	bloody
1	Misc	weary
1	Misc	unable
1	Misc	trusty
1	Misc	further
1	Misc	sacred
1	Misc	tropical
1	Misc	indigenous
1	Misc	temperate
1	Misc	hot
1	Misc	lucky
1	Misc	simple
1	Misc	tiny
1	Misc	hard	
1	Misc	sensational
1	Misc	comparable
1	Misc	angolian
1	Misc	yellow
1	Misc	plodding

# Comparative adjectives.
1	Misc	bloodier
1	Misc	wearier
1	Misc	trustier
1	Misc	hotter
1	Misc	simpler
1	Misc	tinier
1	Misc	harder

# Superlative adjectives.
1	Misc	bloodiest
1	Misc	weariest
1	Misc	trustiest
1	Misc	hottest
1	Misc	simplest
1	Misc	tiniest
1	Misc	hardest

# Plural nouns.
1	Misc	coconuts
1	Misc	halves
1	Misc	snows
1	Misc	mountains
1	Misc	areas
1	Misc	strangers
1	Misc	inches
1	Misc	snakes
1	Misc	ants
1	Misc	nights

# More proper nouns, not people.

1	Misc	Camelot
1	Misc	England
1	Misc	Holy Grail
1	Misc	Round Table

# Plural proper nouns.
1	Misc	Britons
1	Misc	Saxons

# Personal pronouns.
1	Misc	he
1	Misc	her
1	Misc	him
1	Misc	it
1	Misc	one
1	Misc	she
1	Misc	them
1	Misc	they


# Possessive personal pronouns
1	Misc	her
1	Misc	his
1	Misc	its
1	Misc	their

# Adverbs.
1	Misc	again
1	Misc	already
1	Misc	currently
1	Misc	frequently
1	Misc	precisely
1	Misc	south
1	Misc	successfully
1	Misc	unfortunately

# 'do'/'does'
1	Misc	do
1	Misc	does

# 'to'
1	Misc	to

# 'not'
1	Misc	not

# Verbs (base form).
1	Misc	have
1	Misc	speak
1	Misc	cover
1	Misc	be
1	Misc	ride
1	Misc	drink
1	Misc	grow
1	Misc	carry
1	Misc	suggest
1	Misc	migrate
1	Misc	know

# Verbs (past tense).
1	Misc	had
1	Misc	spoke
1	Misc	covered
1	Misc	was
1	Misc	were
1	Misc	rode
1	Misc	drank
1	Misc	grew
1	Misc	carried
1	Misc	suggested
1	Misc	migrated
1	Misc	knew

# Verbs (present participles).
1	Misc	having
1	Misc	speaking
1	Misc	covering
1	Misc	being
1	Misc	riding
1	Misc	drinking
1	Misc	growing
1	Misc	carrying
1	Misc	suggesting
1	Misc	migrating
1	Misc	knowing

# Verbs (past participle).
1	Misc	had
1	Misc	spoken
1	Misc	covered
1	Misc	been
1	Misc	ridden
1	Misc	drunk
1	Misc	grown
1	Misc	carried
1	Misc	suggested
1	Misc	migrated
1	Misc	known

# More third person singular verbs.
1	Misc	speaks
1	Misc	grows
1	Misc	goes
1	Misc	migrates
1	Misc	suggests
1	Misc	knows

# Verbs (present, plural, third person).
1	Misc	have
1	Misc	speak
1	Misc	cover
1	Misc	are
1	Misc	ride
1	Misc	drink
1	Misc	grow
1	Misc	carry
1	Misc	suggest
1	Misc	migrate
1	Misc	know

# Wh-determiners.
1	Misc	that
1	Misc	what
1	Misc	which

# Wh-pronouns.
1	Misc	what
1	Misc	who

# Wh possessive pronoun.
1	Misc	whose

# Wh-adverbs
1	Misc	how
1	Misc	when
1	Misc	where
1	Misc	why


# Possessive marker.
1	Misc	's
